language: elixir

elixir:
    - '1.6.5'
otp_release:
    - '20.3.6'
    - '19.3.6'

install:
    - bin/ci-install.sh

script:
    - bin/ci-run.sh
    - bin/ci-bench.sh

cache:
    directories:
        - deps
        - _build
