steps:
  - command: "docker build -t plug_instrumenter:latest ."
    label: ":docker: build container"

  - wait

  - command: "docker run --rm plug_instrumenter:latest bin/ci-run.sh"
    label: ":elixir: run tests"
